INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Rouge', 35,  1);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Blanc', 29, 1);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Noir', 31, 1);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Crème', 28, 8);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Rouge', 35,  8);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Blanc', 29, 8);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Noir', 31, 8);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Rouge', 35,  9);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Blanc', 29, 9);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Noir', 31, 9);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Crème', 28, 9);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Parquet', 20, 2);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Moquette', 17, 2);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Parquet', 20, 10);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Moquette', 17, 10);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Simple', 300, 3);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Double vitrage', 500, 3);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Double vitrage et discret', 750, 3);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Simple', 300, 12);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Double vitrage', 500, 12);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Double vitrage et discret', 750, 12);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Simple', 300, 19);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Double vitrage', 500, 19);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Double vitrage et discret', 750, 19);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Roulant', 700, 4);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Roulant et électrique', 1200, 4);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Roulant', 700, 13);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Roulant et électrique', 1200, 13);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Halogène', 50,  5);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('LED', 70, 5);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Halogène', 50,  7);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('LED', 70, 7);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Halogène', 50,  11);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('LED', 70, 11);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Granit', 25, 6);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Ardoise', 35, 6);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('IsolantMarbre', 40, 6);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Synthétique', 200, 14);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Naturel', 350, 14);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Biologique', 550, 14);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Synthétique', 200, 18);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Naturel', 350, 18);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Biologique', 550, 18);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Tuiles', 100, 15);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Ardoise', 150, 15);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Bois', 120, 15);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Tuiles', 100, 17);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Ardoise', 150, 17);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Bois', 120, 17);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Manuelle', 2000, 16);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Electrique', 3000, 16);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Débordement', 12000, 20);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Biologique', 20000, 20);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Naturelle', 35000, 20);
INSERT INTO ValCarac (libelle_ValCarac, prix_ValCarac, Caractéristiques_idCaractéristiques) VALUES ('Intérieure', 55000, 20);